# Generated by Django 2.2.4 on 2019-09-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id_num', models.IntegerField(primary_key=True, serialize=False)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learn_model.Person')),
            ],
        ),
    ]
