# Generated by Django 2.2.4 on 2019-09-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_model', '0002_idcard_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamborghini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
